SELECT EmployeeID, Fname, Lname, Role FROM EMPLOYEE;
SELECT EmployeeID, Specialization, MedicalQualifications, LicenseNumber FROM DOCTOR;

SELECT PatientID, Fname, Lname FROM PATIENT;

SELECT * FROM EQUIPMENT;

SELECT * FROM PRESCRIPTION;
SELECT * FROM PRESCRIPTION_INVENTORY;

SELECT * FROM BILLING;

SELECT PatientID, Fname, Lname, ContactNo FROM PATIENT;

SELECT * FROM APPOINTMENT;

SELECT * FROM INVENTORY;

SELECT * FROM EQUIPMENT;

SELECT * FROM INVENTORY;
SELECT * FROM PRESCRIPTION_INVENTORY;
